Repository google/android-fhir, pull requests merged in 2021-09, with the labels that each got.

#697 Added support to search using multiple resource types
  engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
  engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
  engine/src/main/java/com/google/android/fhir/search/NestedSearch.kt
  engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
  engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
Labels: Q3 2021

#742 Hidden extension to hide question item.
  datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Labels: bug

#776 Reference app crash when country is null.
  reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
  reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
Labels: bug

#756 Add response item initial value to questionnaire response only if enablewhen is true.
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Labels: bug

#698 New data capture library widget: MultiSelect
  datacapture/src/androidTest/AndroidManifest.xml
  datacapture/src/androidTest/java/com/google/android/fhir/datacapture/TestActivity.kt
  datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMultiSelectHolderFactoryInstrumentedTest.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderType.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/MultiSelectDialogFragment.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMultiSelectViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
  datacapture/src/main/res/layout/questionnaire_item_multi_select_dialog.xml
  datacapture/src/main/res/layout/questionnaire_item_multi_select_item.xml
  datacapture/src/main/res/layout/questionnaire_item_multi_select_view.xml
  datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderTypeTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItemTest.kt
  datacapturegallery/src/main/assets/generic-health-assessment-example.json
Labels: Q3 2021

#721 Risk assessment display.
  reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
  reference/src/main/java/com/google/android/fhir/reference/PatientDetailsRecyclerViewAdapter.kt
  reference/src/main/java/com/google/android/fhir/reference/PatientDetailsViewModel.kt
  reference/src/main/java/com/google/android/fhir/reference/PatientItemRecyclerViewAdapter.kt
  reference/src/main/java/com/google/android/fhir/reference/PatientItemViewHolder.kt
  reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
  reference/src/main/java/com/google/android/fhir/reference/ScreenerViewModel.kt
  reference/src/main/res/layout/patient_details_header.xml
  reference/src/main/res/layout/patient_list_item_view.xml
  reference/src/main/res/values/colors.xml
  reference/src/main/res/values/strings.xml
Labels: Q3 2021

#785 Screener questionnaire ui alignment issues.
  reference/src/main/assets/screener-questionnaire.json
Labels: Q3 2021

#730 Applying validation on bind to keep validation message relavant to current questionnaireItemViewItem
  datacapture/src/main/java/com/google/android/fhir/datacapture/validation/QuestionnaireResponseItemValidator.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDisplayViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemGroupViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMultiSelectViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSliderViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
  datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/CustomNumberPickerFactory.kt
Labels: bug, data-capture

#792 Navigation drawer with sync menu and last sync time.
  reference/src/main/java/com/google/android/fhir/reference/AddPatientFragment.kt
  reference/src/main/java/com/google/android/fhir/reference/EditPatientFragment.kt
  reference/src/main/java/com/google/android/fhir/reference/MainActivity.kt
  reference/src/main/java/com/google/android/fhir/reference/MainActivityViewModel.kt
  reference/src/main/java/com/google/android/fhir/reference/PatientDetailsFragment.kt
  reference/src/main/java/com/google/android/fhir/reference/PatientListFragment.kt
  reference/src/main/res/layout/activity_main.xml
  reference/src/main/res/layout/drawer_header_layout.xml
  reference/src/main/res/menu/drawer_menu.xml
  reference/src/main/res/values/dimens.xml
  reference/src/main/res/values/strings.xml
Labels: Q3 2021

#754 Added code for answerOption lookups from external and contained ValueSet Resource
  datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactoryInstrumentedTest.kt
  datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactoryInstrumentedTest.kt
  datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryInstrumentedTest.kt
  datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactoryInstrumentedTest.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemMultiSelectViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Labels: Q3 2021
