Repository google/android-fhir, pull requests merged in 2021-03, with the labels that each got.

#304 Convert APIs to suspend functions
  core/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
  core/src/main/java/com/google/android/fhir/FhirEngine.kt
  core/src/main/java/com/google/android/fhir/db/Database.kt
  core/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
  core/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
  core/src/main/java/com/google/android/fhir/search/Search.kt
  core/src/main/java/com/google/android/fhir/search/impl/SearchImpl.kt
  core/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
  datacapture/build.gradle
  reference/build.gradle
  reference/src/main/java/com/google/android/fhir/reference/PatientListActivity.kt
  reference/src/main/java/com/google/android/fhir/reference/PatientListViewModel.kt
Labels: enhancement

#389 Add prefill example back to the application
  datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireContainerFragment.kt
  datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireListFragment.kt
  datacapturegallery/src/main/java/com/google/android/fhir/datacapture/gallery/QuestionnaireViewModel.kt
Labels: bug

#352 process: Added issue templates- Code-Health, Research, Process
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/code_health.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/process.md
  .github/ISSUE_TEMPLATE/research.md
Labels: process

#405 Use Kotlin `vararg` to combine solo and batch APIs in `FhirEngine` and `Database`
  core/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
  core/src/main/java/com/google/android/fhir/FhirEngine.kt
  core/src/main/java/com/google/android/fhir/db/Database.kt
  core/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
  core/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
  core/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
Labels: code health
