Repository google/android-fhir, pull requests merged in 2022-07, with the labels that each got.

#1399 Support Stringtype, Integertype as answer option type when item type is choice.
  datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/MoreAnswerOptionsTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryTest.kt
Labels: P1

#1372 showing downloaded patient list from DB if sync Api fails in between
  demo/src/main/java/com/google/android/fhir/demo/MainActivity.kt
  demo/src/main/java/com/google/android/fhir/demo/PatientListFragment.kt
  demo/src/main/res/anim/fade_in.xml
  demo/src/main/res/anim/fade_out.xml
  demo/src/main/res/drawable/ic_baseline_sync_24.xml
  demo/src/main/res/layout/fragment_patient_list.xml
  demo/src/main/res/layout/sync_status_layout.xml
  demo/src/main/res/values/colors.xml
  demo/src/main/res/values/strings.xml
Labels: P2

#1478 1420 make lastupdated configurable
  datacapture/src/main/java/com/google/android/fhir/datacapture/MoreAnswerOptions.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapter.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemCheckBoxGroupViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/MoreAnswerOptionsTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemAdapterTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactoryTest.kt
  engine/src/main/java/com/google/android/fhir/sync/Config.kt
  engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt
  engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManagerTest.kt
  engine/src/test/java/com/google/android/fhir/sync/upload/BundleUploaderTest.kt
  engine/src/test/java/com/google/android/fhir/sync/upload/TransactionBundleGeneratorTest.kt
Labels: Bug, FHIR engine, P1

#1488 Rename attributes and default styles.
  catalog/src/main/res/values-night/themes.xml
  catalog/src/main/res/values/styles.xml
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemAutoCompleteViewHolderFactory.kt
  datacapture/src/main/res/layout/input_error_text_view.xml
  datacapture/src/main/res/layout/questionnaire_fragment.xml
  datacapture/src/main/res/layout/questionnaire_item_boolean_type_picker_view.xml
  datacapture/src/main/res/layout/questionnaire_item_check_box_view.xml
  datacapture/src/main/res/layout/questionnaire_item_date_picker_view.xml
  datacapture/src/main/res/layout/questionnaire_item_date_time_picker_view.xml
  datacapture/src/main/res/layout/questionnaire_item_drop_down_list.xml
  datacapture/src/main/res/layout/questionnaire_item_drop_down_view.xml
  datacapture/src/main/res/layout/questionnaire_item_edit_text_auto_complete_view.xml
  datacapture/src/main/res/layout/questionnaire_item_edit_text_view.xml
  datacapture/src/main/res/layout/questionnaire_item_header.xml
  datacapture/src/main/res/layout/questionnaire_item_multi_select_dialog.xml
  datacapture/src/main/res/layout/questionnaire_item_option_item_multi.xml
  datacapture/src/main/res/layout/questionnaire_item_option_item_other_add_another.xml
  datacapture/src/main/res/layout/questionnaire_item_option_item_other_text.xml
  datacapture/src/main/res/layout/questionnaire_item_option_item_single.xml
  datacapture/src/main/res/layout/questionnaire_item_option_select_view.xml
  datacapture/src/main/res/layout/questionnaire_item_radio_button.xml
  datacapture/src/main/res/values/attrs.xml
  datacapture/src/main/res/values/styles.xml
Labels: P2, Data capture, ux

#1384 Fix FHIR Engine search sort for DateTime properties
  engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
  engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
Labels: P1

#1466 Adds Gradle task `dokkaHtml` to run Dokka document generation
  buildSrc/src/main/kotlin/Plugins.kt
  datacapture/build.gradle.kts
  engine/build.gradle.kts
  workflow/build.gradle.kts
Labels: P2

#1481 Try Kokoro as CI Tool
  .github/workflows/ci.yml
  .github/workflows/deviceTests.yml
  datacapture/src/main/res/layout/questionnaire_item_multi_select_dialog.xml
  datacapture/src/main/res/values/strings.xml
  engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
  kokoro/README.md
  kokoro/gcp_ubuntu/common.cfg
  kokoro/gcp_ubuntu/continuous.cfg
  kokoro/gcp_ubuntu/kokoro_build.sh
  kokoro/gcp_ubuntu/presubmit.cfg
  settings.gradle.kts
  testing/build.gradle.kts
Labels: P2, Builds

#1470 Improve Kdoc comments for QuestionnaireFragment.
  datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
Labels: P2

#1335 Changes to handle conflicts during download
  demo/src/main/java/com/google/android/fhir/demo/data/FhirPeriodicSyncWorker.kt
  engine/src/main/java/com/google/android/fhir/FhirEngine.kt
  engine/src/main/java/com/google/android/fhir/db/Database.kt
  engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
  engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
  engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeUtils.kt
  engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
  engine/src/main/java/com/google/android/fhir/sync/ConflictResolver.kt
  engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
  engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
  engine/src/main/java/com/google/android/fhir/sync/Sync.kt
  engine/src/main/java/com/google/android/fhir/sync/SyncJob.kt
  engine/src/main/java/com/google/android/fhir/sync/SyncJobImpl.kt
  engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
  engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
  engine/src/test/java/com/google/android/fhir/sync/AcceptLocalConflictResolverTest.kt
  engine/src/test/java/com/google/android/fhir/sync/AcceptRemoteConflictResolverTest.kt
  engine/src/test/java/com/google/android/fhir/sync/FhirSyncWorkerTest.kt
  engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
  engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
  engine/src/test/java/com/google/android/fhir/sync/TestSyncWorker.kt
Labels: Enhancement, FHIR engine, P1
