Repository google/android-fhir, pull requests merged in 2022-03, with the labels that each got.

#1213 Refactored nestedQuery() function to not mutate the passed function args.
  engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
  engine/src/main/java/com/google/android/fhir/search/NestedSearch.kt
Labels: Code health

#1206 [1205] FhirEngine Sync Download API Re-design
  demo/src/main/java/com/google/android/fhir/demo/data/DownloadManagerImpl.kt
  demo/src/main/java/com/google/android/fhir/demo/data/FhirPeriodicSyncWorker.kt
  engine/src/main/java/com/google/android/fhir/sync/Config.kt
  engine/src/main/java/com/google/android/fhir/sync/DownloadManager.kt
  engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
  engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
  engine/src/main/java/com/google/android/fhir/sync/Sync.kt
  engine/src/main/java/com/google/android/fhir/sync/SyncJob.kt
  engine/src/main/java/com/google/android/fhir/sync/SyncJobImpl.kt
  engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
  engine/src/test/java/com/google/android/fhir/sync/FhirSyncWorkerTest.kt
  engine/src/test/java/com/google/android/fhir/sync/SyncJobTest.kt
  engine/src/test/java/com/google/android/fhir/sync/SyncTest.kt
  engine/src/test/java/com/google/android/fhir/sync/TestFailingSyncWorker.kt
  engine/src/test/java/com/google/android/fhir/sync/TestSyncWorker.kt
Labels: Beta

#1231 Assign a UUID as the logical ID (and return it) of a newly created FHIR resource
  demo/src/main/java/com/google/android/fhir/demo/AddPatientViewModel.kt
  demo/src/main/java/com/google/android/fhir/demo/ScreenerViewModel.kt
  engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
  engine/src/main/java/com/google/android/fhir/FhirEngine.kt
  engine/src/main/java/com/google/android/fhir/db/Database.kt
  engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
  engine/src/main/java/com/google/android/fhir/db/impl/dao/ResourceDao.kt
  engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
  engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
  engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
  workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
Labels: Beta, FHIR engine

#1259 Provide ResourceSyncParams based DownloadManager for syncing data.
  engine/src/main/java/com/google/android/fhir/sync/Config.kt
  engine/src/main/java/com/google/android/fhir/sync/Sync.kt
  engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt
  engine/src/test/java/com/google/android/fhir/sync/download/DownloaderImplTest.kt
  engine/src/test/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManagerTest.kt
Labels: Enhancement, Beta
