Repository google/android-fhir, pull requests merged in 2022-01, with the labels that each got.

#810 Implement the `evaluateMeasure` API in the `FhirOperator.kt` class
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/LicenseeConfig.kt
  catalog/build.gradle.kts
  datacapture/build.gradle.kts
  workflow/build.gradle.kts
  workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineDal.kt
  workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineLibraryContentProvider.kt
  workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineRetrieveProvider.kt
  workflow/src/main/java/com/google/android/fhir/workflow/FhirEngineTerminologyProvider.kt
  workflow/src/main/java/com/google/android/fhir/workflow/FhirOperator.kt
  workflow/src/test/java/com/google/android/fhir/workflow/ExampleUnitTest.kt
  workflow/src/test/java/com/google/android/fhir/workflow/FhirOperatorTest.kt
  workflow/testdata/first-contact/01-registration/patient-charity-otala-1.json
  workflow/testdata/first-contact/02-enrollment/careplan-charity-otala-1-pregnancy-plan.xml
  workflow/testdata/first-contact/02-enrollment/episodeofcare-charity-otala-1-pregnancy-episode.xml
  workflow/testdata/first-contact/03-contact/encounter-anc-encounter-charity-otala-1.xml
Labels: Q4 2021

#920 Changes to use logical operator instead of Set operators while generating Search SQL query
  buildSrc/build.gradle.kts
  engine/src/main/java/com/google/android/fhir/search/MoreSearch.kt
  engine/src/main/java/com/google/android/fhir/search/NestedSearch.kt
  engine/src/main/java/com/google/android/fhir/search/SearchDsl.kt
  engine/src/main/java/com/google/android/fhir/search/filter/DateParamFilterCriterion.kt
  engine/src/main/java/com/google/android/fhir/search/filter/FilterCriterion.kt
  engine/src/main/java/com/google/android/fhir/search/filter/NumberParamFilterCriterion.kt
  engine/src/main/java/com/google/android/fhir/search/filter/QuantityParamFilterCriterion.kt
  engine/src/main/java/com/google/android/fhir/search/filter/ReferenceParamFilterCriterion.kt
  engine/src/main/java/com/google/android/fhir/search/filter/StringParamFilterCriterion.kt
  engine/src/main/java/com/google/android/fhir/search/filter/TokenParamFilterCriterion.kt
  engine/src/main/java/com/google/android/fhir/search/filter/UriParamFilterCriterion.kt
  engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
Labels: fhir-engine, code health

#1035 Cleaned up the questionnaire json to have either definition or itemExtractionContext for an item.
  demo/src/main/assets/new-patient-registration-paginated.json
  demo/src/main/assets/screener-questionnaire.json
Labels: Bug

#880 Save the down synced resources of a page as it is dowloaded.
  engine/src/main/java/com/google/android/fhir/FhirEngine.kt
  engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
  engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
  engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
  engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
Labels: Bug

#1074 On Patient registration page, City and Country made mandatory
  demo/src/main/assets/new-patient-registration-paginated.json
Labels: Bug
