Repository google/android-fhir, pull requests merged in 2022-09, with the labels that each got.

#1328 Add variable Extension support
  datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaires.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluator.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/fhirpath/FHIRPathEngineHostServices.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponentsTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/ExpressionEvaluatorTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/fhirpath/FHIRPathEngineHostServicesTest.kt
Labels: P2

#1573 Set answer properly to radio button input
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemRadioGroupViewHolderFactory.kt
Labels: Bug, Data capture

#1581 Clearing the old state of date and date-time ViewHolders
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactory.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDateTimePickerViewHolderFactoryTest.kt
Labels: Bug, Data capture

#1442 Restricting DatePicker to select date from outside the defined Range (Min/Max). Added support for fhir path expression in Min / Max Validators
  datacapture/src/androidTest/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactoryEspressoTest.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireItemComponents.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidator.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidator.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/validation/ValidationUtil.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDatePickerViewHolderFactory.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MaxValueConstraintValidatorTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/validation/MinValueConstraintValidatorTest.kt
Labels: P2

#1584 Configurable Bundle size to upload to the server
  engine/src/main/java/com/google/android/fhir/sync/Config.kt
  engine/src/main/java/com/google/android/fhir/sync/FhirSyncWorker.kt
  engine/src/main/java/com/google/android/fhir/sync/FhirSynchronizer.kt
  engine/src/main/java/com/google/android/fhir/sync/Sync.kt
  engine/src/main/java/com/google/android/fhir/sync/SyncJob.kt
  engine/src/main/java/com/google/android/fhir/sync/SyncJobImpl.kt
  engine/src/main/java/com/google/android/fhir/sync/upload/BundleUploader.kt
  engine/src/main/java/com/google/android/fhir/sync/upload/LocalChangesPaginator.kt
  engine/src/test/java/com/google/android/fhir/sync/upload/BundleUploaderTest.kt
  engine/src/test/java/com/google/android/fhir/sync/upload/LocalChangesPaginatorTest.kt
  engine/src/test/java/com/google/android/fhir/sync/upload/TransactionBundleGeneratorTest.kt
Labels: Enhancement
