Repository google/android-fhir, pull requests merged in 2022-08, with the labels that each got.

#1517 Make multi-line text widget taller by default
  datacapture/src/main/java/com/google/android/fhir/datacapture/DataCaptureConfig.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/contrib/views/QuestionnaireItemPhoneNumberViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/StructureMapExtractionContext.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextDecimalViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextIntegerViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextMultiLineViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextQuantityViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextSingleLineViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextStringViewHolderDelegate.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemEditTextViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewHolderFactory.kt
  datacapture/src/main/res/layout/questionnaire_item_edit_text_multi_line_view.xml
  datacapture/src/main/res/layout/questionnaire_item_edit_text_single_line_view.xml
Labels: ux

#1479 Add X-FHIR-Query support in the FHIR Engine library
  engine/src/main/java/com/google/android/fhir/MoreResources.kt
  engine/src/main/java/com/google/android/fhir/Util.kt
  engine/src/main/java/com/google/android/fhir/search/Search.kt
  engine/src/main/java/com/google/android/fhir/search/filter/TokenParamFilterCriterion.kt
  engine/src/main/java/com/google/android/fhir/search/query/XFhirQueryTranslator.kt
  engine/src/test/java/com/google/android/fhir/MoreResourcesTest.kt
  engine/src/test/java/com/google/android/fhir/UtilTest.kt
  engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
  engine/src/test/java/com/google/android/fhir/search/SearchTest.kt
  engine/src/test/java/com/google/android/fhir/search/query/XFhirQueryTranslatorTest.kt
Labels: FHIR engine, P1

#1487 Purge API implemented
  engine/src/androidTest/java/com/google/android/fhir/db/impl/DatabaseImplTest.kt
  engine/src/main/java/com/google/android/fhir/FhirEngine.kt
  engine/src/main/java/com/google/android/fhir/LocalChange.kt
  engine/src/main/java/com/google/android/fhir/db/Database.kt
  engine/src/main/java/com/google/android/fhir/db/impl/DatabaseImpl.kt
  engine/src/main/java/com/google/android/fhir/db/impl/dao/LocalChangeDao.kt
  engine/src/main/java/com/google/android/fhir/impl/FhirEngineImpl.kt
  engine/src/test-common/java/com/google/android/fhir/resource/TestingUtils.kt
  engine/src/test/java/com/google/android/fhir/impl/FhirEngineImplTest.kt
Labels: FHIR engine, P1

#1561 Fix for swapped or cleared answers in Open choice/Drop Down View.
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDialogSelectViewHolderFactory.kt
Labels: Bug, Data capture

#1562 Fix for dropdown showing up again on answer change.
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemDropDownViewHolderFactory.kt
Labels: Bug, Data capture

#1301 Implement the `entryMode` extension
  datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaires.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnairesTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
Labels: P1

#1310 Feature to review question/answers in list view in Questionnaire Fragment
  datacapture/src/androidTest/java/com/google/android/fhir/datacapture/contrib/views/QuestionnaireItemPhoneNumberViewHolderFactoryInstrumentedTest.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/MoreQuestionnaireResponseItemAnswerComponent.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemEditAdapter.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemReviewAdapter.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireItemViewHolderType.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireViewModel.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactory.kt
  datacapture/src/main/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItem.kt
  datacapture/src/main/res/drawable/ic_outline_edit_24.xml
  datacapture/src/main/res/layout/questionnaire_fragment.xml
  datacapture/src/main/res/layout/questionnaire_item_simple_question_answer_view.xml
  datacapture/src/main/res/values/attrs.xml
  datacapture/src/main/res/values/strings.xml
  datacapture/src/main/res/values/styles.xml
  datacapture/src/test/java/com/google/android/fhir/datacapture/MoreQuestionnaireResponseItemAnswerComponentTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemEditAdapterTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireItemReviewAdapterTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/QuestionnaireViewModelTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemSimpleQuestionAnswerDisplayViewHolderFactoryTest.kt
  datacapture/src/test/java/com/google/android/fhir/datacapture/views/QuestionnaireItemViewItemTest.kt
Labels: P1

#1419 Handle indexing of timing with no event or has a repeating timing.
  engine/src/main/java/com/google/android/fhir/index/ResourceIndexer.kt
  engine/src/test/java/com/google/android/fhir/index/ResourceIndexerTest.kt
Labels: P1

#1571 Bump up engine version to 0.1.0-beta02
  buildSrc/src/main/kotlin/Releases.kt
Labels: Beta, FHIR engine
